name: MIKUMBA
favicon: null
layout_spectrum: 0.28732150117866695
typography_spectrum: 0.9981461996212602
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.06358702527359128
  lightness: 0.1373067870736122
  saturation: 0.8747647511772811
  rhythmicContrast: 0.4520929753780365
purpose: []
